var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,f){a!=Array.prototype&&a!=Object.prototype&&(a[c]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var c,f=[];!(c=a.next()).done;)f.push(c.value);return f};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
var Q=function(){};Q.prototype.then=function(a){this.data?a(data):this.cb=a};Q.prototype.resolve=function(a){this.cb?this.cb(a):this.data=a};Q.prototype.reject=function(a){this.err&&this.err(a)};Q.all=function(a){var c=a.length,f=0,g=new Q;a.forEach(function(a){a.then(function(){f+=1;f===c&&g.resolve()})});return g};
var load=function(a){var c=new XMLHttpRequest,f=new Q;c.open("GET","/chapters/"+a+".html");c.onreadystatechange=function(){4===c.readyState&&(200===c.status?(gmtr.emit("loaded",{name:a,loaded:1,total:1}),f.resolve(c.responseText)):f.reject("Could not load data."))};c.onprogress=function(c){gmtr.emit("loaded",{name:a,loaded:c.loaded,total:c.total})};c.send();return f},fitResolution=function(a,c,f,g){var u=window.devicePixelRatio||1,y=c.webkitBackingStorePixelRatio||c.mozBackingStorePixelRatio||c.msBackingStorePixelRatio||
c.oBackingStorePixelRatio||c.backingStorePixelRatio||1,h=u/y;u!==y?(a.width=f*h,a.height=g*h,a.style.width=f+"px",a.style.height=g+"px",c.scale(h,h)):(a.width=f,a.height=g)},calcLen=function(a,c,f,g){return Math.sqrt(Math.pow(f-a,2)+Math.pow(g-c,2))},getAngle=function(a,c,f,g){return Math.atan2(g-c,f-a)},sharedCanvasHelpers={colors:"#1a1a1a #c44126 #cd7c00 #238dcd #e4e000 #e48900 #e43b17 #31cd19 #cd3fc4 #562730".split(" "),getOneColor:function(){return this.colors[randi(0,this.colors.length-1)]}};
function randi(a,c){a=Math.ceil(a);c=Math.floor(c);return Math.floor(Math.random()*(c-a+1))+a}function randix(a,c){var f=randi(a,c);return a!==c&&0===f?randix(a,c):f}
DC.ready(function(){function a(b,a,n){if(b){if("object"===typeof b){var r=b;b=b.page}else r=e.getPage(b);var v=l[b]||DC({c:"chapter"}),f=new Q;l[b]?(p=b,n||c(l[b],b,a),f.resolve()):load(b).then(function(P){p=b;v.h=P||'<div class="chapter-title">'+r.title+"</div>";n?l[b]=v:c(v,b,a);f.resolve()});d.activate(p);return f}}function c(b,a,n){l[a]=b;var r=e.getPage(e.getPrev(a));r&&(r=l[r.page]);r?b.after(r):((r=e.getPage(e.getNext(a)))&&(r=l[r.page]),r?b.before(r):b.into(u));n||(f(),window.scrollTo(0,b.offsetTop-
80))}function f(b){b&&p!==b&&(p=b,d.activate(p));localStorage.setItem("chapter",p)}var g=DC({c:"body"}).into(document.body),u=DC({c:"view"}).into(g),y={},h=DC({c:"controls center"}).into(g),e=[{title:"UABRO - age of consciousness",page:"cover-page"},{title:"Introduction",page:"introduction"},{title:"Intelligent freedom",page:"intelligent-freedom"},{title:"Finale of development",page:"finale-of-development"},{title:"Chaos and order",page:"chaos-and-order"},{title:"Four ways of behavior",page:"four-ways-of-behavior"},
{title:"Priority project",page:"priority-project"},{title:"True, false and simulation",page:"true-or-simulation"},{title:"Ecosystem",page:"ecosystem"},{title:"Focus on",page:"focus-on"},{title:"Infinite beauty of consciousness",page:"infinite-beauty-of-consciousness"},{title:"Not conclusion",page:"not-conclusion"},{title:"Vocabulary",page:"vocabulary"}];e.getIndex=function(b){for(var a=e.length,n=0;n<a;n+=1)if(e[n].page===b)return n};e.getNext=function(b){b=e.getIndex(b);if(!1!==b&&b!==e.length-1)return e[b+
1]};e.getPrev=function(b){b=e.getIndex(b);if(!1!==b&&0!==b)return e[b-1]};e.getPage=function(b){if(b)return"object"===typeof b&&(b=b.page),e.find(function(a){return a.page===b})};var l={},p,m=!1,d=DC({c:"content"});d.render=function(){d.classList.contains("visible-x")?d._hide():(d.addClass("visible-x"),document.body.addClass("no-scroll"),d.scrollTo(0,0))};d._hide=function(){d.removeClass("visible-x");document.body.removeClass("no-scroll")};d.chapters=[];g=DC({c:"content-close-wrap"}).into(d);DC({c:"content-close",
t:"hide",events:{click:function(){d._hide()}}}).into(g);e.forEach(function(b){d.chapters[b.page]=DC("button",{t:b.title,events:{click:function(){a(b.page);m=window.pageYOffset}}}).into(d)});DC({c:"right",h:"<i>by Oleksii Shnyra</i>"}).into(d);d.activate=function(b){d.chapters[b]&&(d.curChapter&&d.curChapter.removeClass("active"),d.curChapter=d.chapters[b],d.curChapter.addClass("active"),H.t=d.curChapter.t,d._hide())};var H=DC("button",{t:"content",c:"title",events:{click:function(){d.render()}},prevented:["click"]});
h.list([H,d]);var I=DC("canvas",{c:"always-canvas"}).into(document.body),t=I.getContext("2d"),F=!1,q=[],A=Math.PI/2,J=function(b){if(!F){if(!b)return;F=!0}else if(b)return;requestAnimationFrame(function(){return J()});fitResolution(I,t,window.innerWidth,window.innerHeight);b=q.length;for(var a=0;a<b-1;a+=1){var n=q[a],c=q[a+1],v=n,f=v.x;v=v.y;var d=c,k=d.x;d=d.y;t.beginPath();var e=t.createLinearGradient(f,v,k,d);e.addColorStop(0,n.c);e.addColorStop(.5,"#46171f");e.addColorStop(1,c.c);t.fillStyle=
e;t.globalAlpha=a/b;e=getAngle(f,v,k,d);t.arc(f,v,n.s,e+A,e-A,!0);t.arc(k,d,c.s,e+A,e-A);t.fill()}0===Date.now()%2&&(q.shift(),q.length||(F=!1))};window.addEventListener("mousemove",function(b){q.push({x:b.clientX,y:b.clientY,c:sharedCanvasHelpers.getOneColor(),s:2});80<=q.length&&q.shift();J(!0)});var G=DC("canvas",{c:"first-canvas"}).into(document.body),w=G.getContext("2d"),B=!1,C=[];g=sharedCanvasHelpers.colors;for(var R=g.length-1,K=0;120>K;K+=1)C.push({s:randi(10,45)/10,x:randi(0,100)/100,y:randi(0,
100)/100,ax:randix(-20,20)/21E3,ay:randix(-20,20)/21E3,c:g[randi(0,R)]});var D=Math.PI/2,L=function(){if(B){var b=window.innerWidth,a=window.innerHeight,c=.05*(b+a),f=window.innerHeight/2,d=window.pageYOffset;d<=f?requestAnimationFrame(L):(B=!1,d=f);fitResolution(G,w,b,a);for(var e=C.length-1,g=0;g<=e;g+=1){var k=C[g],h=k.x+=k.ax,l=k.y+=k.ay;if(1<h||0>h)k.ax=-k.ax,k.x=1<h?1:0;if(1<l||0>l)k.ay=-k.ay,k.y=1<l?1:0;for(h=g+1;h<=e;h+=1){l=C[h];var m=k,p=l,x=$jscomp.makeIterator([m.x*b,m.y*a,p.x*b,p.y*a]);
m=x.next().value;p=x.next().value;var t=x.next().value;x=x.next().value;var q=calcLen(m,p,t,x);if(q<c){w.beginPath();var u=w.createLinearGradient(m,p,t,x);u.addColorStop(0,k.c);u.addColorStop(.5,"#46171f");u.addColorStop(1,l.c);w.fillStyle=u;w.globalAlpha=.9*(1-q/c)*(1-d/f);q=getAngle(m,p,t,x);w.arc(m,p,k.s,q+D,q-D,!0);w.arc(t,x,l.s,q+D,q-D);w.fill()}}}}};g=y.firstCanvas=function(){window.pageYOffset<window.innerHeight/2&&!B&&(B=!0,requestAnimationFrame(L))};DC.onwindow("resize",function(){return fitResolution(G,
w,window.innerWidth,window.innerHeight)});DC.onwindow("scroll",g);var S={"animated-random-sequence":{on:function(){this.fn()},fn:function(){this.mode&&requestAnimationFrame(this.fn.bind(this));this.genText()},init:function(){var b=" qwertyuiopasdfghjklzxcvbnm1234567890()=-+@#%*\u0439\u0446\u0443\u043a\u0435\u043d\u0433\u0448\u0449\u0437\u0445\u0457\u0444\u0456\u0432\u0430\u043f\u0440\u043e\u043b\u0434\u0436\u0454\u044f\u0447\u0441\u043c\u0438\u0442\u044c\u0431\u044eQWERTYUIOPLKJHGFDSAZXCVBNM_$".split("").concat("\ud83d\ude0c",
"\ud83d\ude09","\ud83d\ude31","\ud83d\ude40","\ud83c\udf1f","\ud83c\udf38","\ud83c\udf54"),a="\u0441\u043b\u043e\u0432\u043e \u0441\u0432\u043e\u0431\u043e\u0434\u0430 \u0441\u0432\u0456\u0434\u043e\u043c\u0456\u0441\u0442\u044c \u0432\u043e\u043b\u044f \u0456\u0434\u0435\u044f \u043d\u0430\u0442\u0445\u043d\u0435\u043d\u043d\u044f \u0440\u0430\u0446\u0456\u043e\u043d\u0430\u043b\u044c\u043d\u0456\u0441\u0442\u044c \u0440\u043e\u0437\u0443\u043c \u043c\u0430\u0442\u0435\u0440\u0456\u044f \u0435\u043d\u0435\u0440\u0433\u0456\u044f energy power water money consciousness freedom knowledge".split(" ").map(function(b){return b.split("").reverse()}),
c=[],f=this.ref.t.split("").map(function(b){return DC("span",{t:b})});this.ref.list(f);var d;this.genText=function(){if(c.length){var n=c.pop();var r=!0;d=510<=d?d-511+1:d+1}else n=b[randi(0,b.length-1)],d=randi(0,511),37<randi(0,40)&&c.push.apply(c,[].concat($jscomp.arrayFromIterable(a[randi(0,a.length-1)])));var e=f[d];e?(e.t=n,e.css({color:r?"rgb("+randi(0,155)+","+randi(0,155)+","+randi(0,155)+")":2<randi(0,9)?"#ddd":"#444"})):console.log("err",e,d,f.length)}}}};DC.onwindow("scroll",function(){Object.entries(S).map(function(b){b=
$jscomp.makeIterator(b);var a=b.next().value;b=b.next().value;if(a=b.ref||$("."+a)){b.ref||(b.ref=a,b.init());var c=a.getBoundingClientRect();var d=window.innerWidth,f=window.innerHeight;c=0>c.right||0>c.bottom||c.left>d||c.top>f?!1:a.contains(document.elementFromPoint(c.left,c.top))||a.contains(document.elementFromPoint(c.right,c.top))||a.contains(document.elementFromPoint(c.right,c.bottom))||a.contains(document.elementFromPoint(c.left,c.bottom));c!==b.mode&&((b.mode=c)?b.on&&b.on(a):b.off&&b.off(a))}})});
var M=!1,z=[],N=function(){z.length=0;DC.iterObj(l,function(a,b){z.push({top:b.offsetTop,page:a})});z.sortBy("top");for(var a=window.pageYOffset,c,d,e=z.length-1;e;--e){var g=z[e];if(g.top<a+100){c=g;d=!0;break}}d||(c=z[0]);c&&p!==c.page&&f(c.page)};h.hide();var O=DC({c:"load-animation"}).into(u);O.css({width:0});var E={},T=e.length;gmtr.on("loaded",function(a){E[a.name]||(E[a.name]={});var b=E[a.name];b.loaded=a.loaded;b.total=a.total;var c=0;DC.iterObj(E,function(a,b){c+=b.loaded/b.total});c*=100/
T;O.css({width:c+"%"})});var U=Date.now();Q.all(e.map(function(b){return a(b.page,!0,!0)})).then(function(){M=!0;var b=Date.now()-U;setTimeout(function(){u.clear();e.forEach(function(a){l[a.page].into(u)});h.show();var b=localStorage.getItem("top");a(localStorage.getItem("chapter")||e[0]);"string"===typeof b&&window.scrollTo(0,b);m=b-h.offsetHeight;h.css({top:m});y.firstCanvas&&y.firstCanvas();N()},1256>b?1256-b:0)});DC.onwindow("scroll",function(){var a=window.pageYOffset;M&&(localStorage.setItem("top",
a),setTimeout(N));if(!1===m)m=a;else{var c=h.offsetHeight,d=m-a;a>m?(d<-c&&(d=-c,m=a-c),h.css({top:d/3+"%"})):d&&(m=a,h.css({top:0}))}})});