var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,g){b!=Array.prototype&&b!=Object.prototype&&(b[d]=g.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var d=0;return $jscomp.iteratorPrototype(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var d=b[Symbol.iterator];return d?d.call(b):$jscomp.arrayIterator(b)};var Q=function(){};Q.prototype.then=function(b){this.data?b(data):this.cb=b};Q.prototype.resolve=function(b){this.cb?this.cb(b):this.data=b};
Q.prototype.reject=function(b){this.err&&this.err(b)};Q.all=function(b){var d=b.length,g=0,l=new Q;b.forEach(function(b){b.then(function(){g+=1;g===d&&l.resolve()})});return l};
var load=function(b){var d=new XMLHttpRequest,g=new Q;d.open("GET","/chapters/"+b+".html");d.onreadystatechange=function(){4===d.readyState&&(200===d.status?(gmtr.emit("loaded",{name:b,loaded:1,total:1}),g.resolve(d.responseText)):g.reject("Could not load data."))};d.onprogress=function(d){gmtr.emit("loaded",{name:b,loaded:d.loaded,total:d.total})};d.send();return g};
DC.ready(function(){function b(a,b,q){if(a){if("object"===typeof a){var f=a;a=a.page}else f=e.getPage(a);var D=p[a]||DC({c:"chapter"}),g=new Q;p[a]?(m=a,q||d(p[a],a,b),g.resolve()):load(a).then(function(c){m=a;D.h=c||'<div class="chapter-title">'+f.title+"</div>";q?p[a]=D:d(D,a,b);g.resolve()});c.activate(m);return g}}function d(a,b,q){p[b]=a;var f=e.getPage(e.getPrev(b));f&&(f=p[f.page]);f?a.after(f):((f=e.getPage(e.getNext(b)))&&(f=p[f.page]),f?a.before(f):a.into(x));q||(g(),window.scrollTo(0,a.offsetTop-
80))}function g(a){a&&m!==a&&(m=a,c.activate(m));localStorage.setItem("chapter",m)}function l(a,b){a=Math.ceil(a);b=Math.floor(b);return Math.floor(Math.random()*(b-a+1))+a}function C(a,b){var f=l(a,b);return a!==b&&0===f?C(a,b):f}var h=DC({c:"body"}).into(document.body),x=DC({c:"view"}).into(h),E={},r=DC({c:"controls center"}).into(h),e=[{title:"UABRO - age of intelligent freedom",page:"cover-page"},{title:"Introduction",page:"introduction"},{title:"Intelligent freedom",page:"intelligent-freedom"},
{title:"Finale of development",page:"finale-of-development"},{title:"Chaos and order",page:"chaos-and-order"},{title:"Four ways of behavior",page:"four-ways-of-behavior"},{title:"Priority project",page:"priority-project"},{title:"True, false and simulation",page:"true-or-simulation"},{title:"Ecosystem",page:"ecosystem"},{title:"Focus on",page:"focus-on"},{title:"Infinite beauty of consciousness",page:"infinite-beauty-of-consciousness"},{title:"Not conclusion",page:"not-conclusion"},{title:"Vocabulary",
page:"vocabulary"}];e.getIndex=function(a){for(var b=e.length,q=0;q<b;q+=1)if(e[q].page===a)return q};e.getNext=function(a){a=e.getIndex(a);if(!1!==a&&a!==e.length-1)return e[a+1]};e.getPrev=function(a){a=e.getIndex(a);if(!1!==a&&0!==a)return e[a-1]};e.getPage=function(a){if(a)return"object"===typeof a&&(a=a.page),e.find(function(b){return b.page===a})};var p={},m,k=!1,c=DC({c:"content"});c.render=function(){c.classList.contains("visible-x")?c._hide():(c.addClass("visible-x"),document.body.addClass("no-scroll"),
c.scrollTo(0,0))};c._hide=function(){c.removeClass("visible-x");document.body.removeClass("no-scroll")};c.chapters=[];h=DC({c:"content-close-wrap"}).into(c);DC({c:"content-close",t:"hide",events:{click:function(){c._hide()}}}).into(h);e.forEach(function(a){c.chapters[a.page]=DC("button",{t:a.title,events:{click:function(){b(a.page);k=window.pageYOffset}}}).into(c)});DC({c:"right",h:"<i>by Oleksii Shnyra</i>"}).into(c);c.activate=function(a){c.chapters[a]&&(c.curChapter&&c.curChapter.removeClass("active"),
c.curChapter=c.chapters[a],c.curChapter.addClass("active"),G.t=c.curChapter.t,c._hide())};var G=DC("button",{t:"content",c:"title",events:{click:function(){c.render()}},prevented:["click"]});r.list([G,c]);var F=DC("canvas",{c:"first-canvas"}).into(document.body),u=F.getContext("2d"),y=!1,H=function(a,b,q,c){var f=window.devicePixelRatio||1,d=b.webkitBackingStorePixelRatio||b.mozBackingStorePixelRatio||b.msBackingStorePixelRatio||b.oBackingStorePixelRatio||b.backingStorePixelRatio||1,e=f/d;f!==d?(a.width=
q*e,a.height=c*e,a.style.width=q+"px",a.style.height=c+"px",b.scale(e,e)):(a.width=q,a.height=c)},z=[];h="#1a1a1a #c44126 #cd7c00 #238dcd #e4e000 #e48900 #e43b17 #31cd19 #cd3fc4 #562730".split(" ");for(var N=h.length-1,I=0;120>I;I+=1)z.push({s:l(10,45)/10,x:l(0,100)/100,y:l(0,100)/100,ax:C(-20,20)/21E3,ay:C(-20,20)/21E3,c:h[l(0,N)]});var A=Math.PI/2,J=function(){if(y){var a=window.innerWidth,b=window.innerHeight,c=.05*(a+b),d=window.innerHeight/2,e=window.pageYOffset;e<=d?requestAnimationFrame(J):
(y=!1,e=d);H(F,u,a,b);for(var g=z.length-1,p=0;p<=g;p+=1){var n=z[p],h=n.x+=n.ax,k=n.y+=n.ay;if(1<h||0>h)n.ax=-n.ax,n.x=1<h?1:0;if(1<k||0>k)n.ay=-n.ay,n.y=1<k?1:0;for(h=p+1;h<=g;h+=1){k=z[h];var l=n,m=k,v=$jscomp.makeIterator([l.x*a,l.y*b,m.x*a,m.y*b]);l=v.next().value;m=v.next().value;var r=v.next().value;v=v.next().value;var w=Math.sqrt(Math.pow(r-l,2)+Math.pow(v-m,2));if(w<c){u.beginPath();var t=u.createLinearGradient(l,m,r,v);t.addColorStop(0,n.c);t.addColorStop(.5,"#46171f");t.addColorStop(1,
k.c);u.fillStyle=t;u.globalAlpha=.85*(1-w/c)*(1-e/d);w=Math.atan2(v-m,r-l);u.arc(l,m,n.s,w+A,w-A,!0);u.arc(r,v,k.s,w+A,w-A);u.fill()}}}}};h=E.firstCanvas=function(){window.pageYOffset<window.innerHeight/2&&!y&&(y=!0,requestAnimationFrame(J))};DC.onwindow("resize",function(){return H(F,u,window.innerWidth,window.innerHeight)});DC.onwindow("scroll",h);var K=!1,t=[],L=function(){t.length=0;DC.iterObj(p,function(a,b){t.push({top:b.offsetTop,page:a})});t.sortBy("top");for(var a=window.pageYOffset,b,c,
d=t.length-1;d;--d){var e=t[d];if(e.top<a+100){b=e;c=!0;break}}c||(b=t[0]);b&&m!==b.page&&g(b.page)};r.hide();var M=DC({c:"load-animation"}).into(x);M.css({width:0});var B={},O=e.length;gmtr.on("loaded",function(a){B[a.name]||(B[a.name]={});var b=B[a.name];b.loaded=a.loaded;b.total=a.total;var c=0;DC.iterObj(B,function(a,b){c+=b.loaded/b.total});c*=100/O;M.css({width:c+"%"})});var P=Date.now();Q.all(e.map(function(a){return b(a.page,!0,!0)})).then(function(){K=!0;var a=Date.now()-P;setTimeout(function(){x.clear();
e.forEach(function(a){p[a.page].into(x)});r.show();var a=localStorage.getItem("top");b(localStorage.getItem("chapter")||e[0]);"string"===typeof a&&window.scrollTo(0,a);k=a-r.offsetHeight;r.css({top:k});E.firstCanvas&&E.firstCanvas();L()},1256>a?1256-a:0)});DC.onwindow("scroll",function(){var a=window.pageYOffset;K&&(localStorage.setItem("top",a),setTimeout(L));if(!1===k)k=a;else{var b=r.offsetHeight,c=k-a;a>k?(c<-b&&(c=-b,k=a-b),r.css({top:c/3+"%"})):c&&(k=a,r.css({top:0}))}})});